[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "799nZHCJvaNUGAqh9AhbRzwPGReimxVjQ29uDPo4bTYZ"

[programs.devnet]
anchor_counter = "799nZHCJvaNUGAqh9AhbRzwPGReimxVjQ29uDPo4bTYZ"

[programs.mainnet]
anchor_counter = "799nZHCJvaNUGAqh9AhbRzwPGReimxVjQ29uDPo4bTYZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"
# wallet = "/home/solana-program/id1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
